### ISSUE TITLE
Can other priors be used in this package? 

### ISSUE THREAD

**Issue by LfeiXie** [ethan-alt/surbayes#1]
Hi, Can the package implement the DMC or Gibbs sample for SUR models with other informative priors (e.g. the multivariate normal distribution) or non-informative priors (e.g. uniform distribution or Jeffreys' prior) ?

**Comment by ethan-alt** [comment]
Jeffreys' prior is already implemented in the package via DMC, and DMC does not work with informative priors. For Gibbs sampling with MVN, you might consider using the bayesm package.

I am unaware of any packages eliciting uniform improper priors, but in principle it should be easy to make one yourself because the full conditionals are available in closed form.
